services:
  weather-scanner:
    image: nsmith167/weather-scanner:latest
    platform: linux/arm/v7
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - WEATHER_ZIP=${WEATHER_ZIP}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - WEATHER_TOPIC=${WEATHER_TOPIC}
      - DEVICE_NAME=${DEVICE_NAME}